version: '3.8'

services:
  backend:
    container_name: oaky-nestjs-app
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3435:3200"
    volumes:
      - ./backend/database:/app/database

  frontend:
    container_name: oaky-react-app
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3434:3000"
    depends_on:
      - backend
    environment:
      - API_URL=http://oakyb.amirdouzandeh.me/graphql
