version: '3.8'

services:
  backend:
    image: amirzenoozi/oaky-interview-backend:latest
    container_name: oaky-nestjs-app
    ports:
      - "3435:3200"
    volumes:
      - ./backend/database:/app/database

  frontend:
    image: amirzenoozi/oaky-interview-frontend:latest
    container_name: oaky-react-app
    ports:
      - "3434:3000"
    depends_on:
      - backend
